; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200

; build_flags =
;   -DCORE_DEBUG_LEVEL=5  
;    -DCORE_DEBUG_LEVEL=0


[env:esp32s3]
platform = espressif32
board = adafruit_metro_esp32s3
framework = arduino
monitor_speed = 115200
board_build.partitions = default_16MB.csv

build_flags =
  -D CONFIG_SPIRAM_SUPPORT=1
  -DCORE_DEBUG_LEVEL=5  
;  -DCORE_DEBUG_LEVEL=0
