[common]
platform = espressif32
framework = arduino
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=5  
;  -DCORE_DEBUG_LEVEL=0

; [env:esp32dev]
; board = esp32dev
; platform = ${common.platform}
; framework = ${common.framework}
; monitor_speed =  ${common.monitor_speed}
; build_flags = ${common.build_flags}


[env:esp32s3]
board = adafruit_metro_esp32s3
platform = ${common.platform}
framework = ${common.framework}
monitor_speed =  ${common.monitor_speed}
board_build.partitions = default_16MB.csv
build_flags =
  -D CONFIG_SPIRAM_SUPPORT=1
   ${common.build_flags}
  
