site_name: Meowui Docs

nav:
    - Про проєкт: about.md
    - Можливості: features.md
    - Налаштування: setup.md
    - Контекст: context.md
    - Обробка вводу: input.md
    - Макети UI: ui.md
    - Ігровий рушій: game_engine.md
    - Підтримка: support.md

theme: readthedocs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences